### ISSUE TITLE
Project status and Java version

### ISSUE THREAD

**Issue by fallmake** [rhilker/ReadXplorer#5]
First of all - impressive and cool project looking at it from a non-researcher/layman perspective. Thank you Dr. Hilker and everyone involved for this software as a free option. I have a few general questions I hope you could answer:

1. Project Status
    1. is it alive and planned to be developed further?
    2. Are forks/pull requests welcome or encouraged?
    3. Is there some sort of (maybe unofficial?) roadmap of some sort regarding planned or desirable features?
2.  A short while ago I helped a friend of mine setting up ReadXplorer when the .exe installers with the included java version weren't available because some of the download links were dead (pointed to an old, decommissioned FTP server at uni Giessen). The links have since been fixed.
    1. Because of Oracle's policies and Java no longer being free of charge, some institutions do no longer allow installing Java. When my friend tried to set up ReadXplorer with a lab colleague using OpenJDK, they couldn't get it to run due to an error saying _cannot find java 1.7 or higher_. I tried different versions and had the same result. It only works when using OpenJDK 8. All newer versions lead to this error, regardless of PATH or JAVA_HOME variable content. Is this deemed fine or are there any necessary or planned changes?

**Comment by oschwengers** [comment]
Dear @fallmake , thanks for reaching out.
Currently, we have no dedicated developer resources for this project but we try to fix bugs and are currently in a major code review in order to decide if and how we will further maintain this project.
Since @rhilker (former main developer) is no longer working on this project, please use this new fork https://github.com/ag-computational-bio/ReadXplorer which is the active repository.
Of course, forks and pull requests are highly welcome! But as we're in the middle of a larger code refactoring, I'd rather suggest to wait in order to produce not too many merge conflicts.

**Comment by fallmake** [comment]
Thank you very much for the response. I'm not sure I completely understand - does the decision to be made based on the code review decide whether ReadXplorer will be continued as a project in general, including the fork being maintained or shut down, or just whether this specific repository of @rhilker will be kept alive while the new fork will stay alive regardless? Doing a larger code refactoring on the fork right now - before this code review and decision - makes it sound like the latter to me.

**Comment by oschwengers** [comment]
As this repository is a private repository of @rhilker , we cannot make any decisions for this specific repository.
However, we're indeed working on the above mentioned fork. We're working to update and review the code base in order to ease all necessary maintenance. Based on the outcome thereof, we'll make a decision regarding any further progress on this project. 

In all cases, I'd like to kindly ask you to move all issues, requests, PR, etc to this actively maintained repo: https://github.com/ag-computational-bio/ReadXplorer Hence, I'll close this issue. But please, feel free and welcome to open new ones in the other repo.
Thanks a lot and best regards!
